### ISSUE TITLE
Turnout integration

### ISSUE THREAD

**Issue by matt-hu** [trainlink-org/trainlink-api#1]
@asbelos, I am about to start integrating turnout into the TrainLink server. You clearly don't like the way it has been done on JMRI, so I would like to avoid their mistakes and do it the 'proper' way. How should I go about doing it. Should I just read the turnouts off the EEPROM and not allow the creation or deletion of new ones? Should I store a list of them in the server in an XML or JSON and avoid the EEPROM entirely? What is the best way?

**Comment by Asbelos** [comment]
The reason the jmri way is bad is because some turnouts are known by the command station ( as in the existing <T> commands ) but others are handled by sending accessory packets or output pin requests so the command station has no way if knowing  what is or isnt a turnout or of tracking its state.This isnt sustainable for users who want to run without Jmri, With either just Engine Driver or TPL.So, at the very least, the T command needs extending to allow many more hardware types, including bus types, to be defined so every turnout can be switched with the same T command.Now, IMHO it seems much more sensible to define all turnouts, signals, sensors,outputs in an easily edited file and have that loaded into the CS.. and i can only think of one method that takes just 1 click to do and doesnt require extra Cs code to do.....  all discussions about EEPROM, SDcard etc are irrelevant if you cant make it easily usable.On 21 Nov 2020 11:43, Matt <notifications@github.com> wrote:
@Asbelos, I am about to start integrating turnout into the TrainLink server. You clearly don't like the way it has been done on JMRI, so I would like to avoid their mistakes and do it the 'proper' way. How should I go about doing it. Should I just read the turnouts off the EEPROM and not allow the creation or deletion of new ones? Should I store a list of them in the server in an XML or JSON and avoid the EEPROM entirely? What is the best way?

**Comment by matt-hu** [comment]
@Asbelos Thanks for the feedback. So, if I stick to just the ones listed by the `<T>` command, this should in theory future proof it for TPL? I realise that TPL might change as it is very much an active discussion.

**Comment by Asbelos** [comment]
No... because TPL runs in the command station without JMRI.. so the layout details will need to be created without T commands. Currently i have tpl code for dcc, servo, pin and i2cpin turnouts... others may be added. You can still switch a turnout with a T command but you cant define a new one in the fly. Im not familiar with trainlink.. is that calling the Cs or just another turnout tech?On 21 Nov 2020 17:44, Matt <notifications@github.com> wrote:
@Asbelos Thanks for the feedback. So, if I stick to just the ones listed by the <T> command, this should in theory future proof it for TPL? I realise that TPL might change as it is very much an active discussion.

**Comment by matt-hu** [comment]
@Asbelos TrainLink is a protocol to allow CS to be controlled over WiFi, similar to WiThrottle but with a greater focus on cross-platform support (mobile and desktop currently supported, ESP32 client to come). You have a client, running on, say, your phone, and a server, which currently runs on a PC connected to the CS over usb. I would like to make as much use as TPL as possible, as I think it is a great system, Will it be possible to start TPL scripts and such over usb, so something like the TrainLink server could start TPL running?

**Comment by Asbelos** [comment]
Yes there are new commands to do this.. look in the docs folder of the TPL branch of CommandStationOn 21 Nov 2020 18:16, Matt <notifications@github.com> wrote:
@Asbelos TrainLink is a protocol to allow CS to be controlled over WiFi, similar to WiThrottle but with a greater focus on cross-platform support (mobile and desktop currently supported, ESP32 client to come). You have a client, running on, say, your phone, and a server, which currently runs on a PC connected to the CS over usb. I would like to make as much use as TPL as possible, as I think it is a great system, Will it be possible to start TPL scripts and such over usb, so something like the TrainLink server could start TPL running?
